// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSV-rxbDSVqRqa8uUswF0sX6vhCq8Z0qw',
    appId: '1:1085913126533:web:04786694694d2536763bec',
    messagingSenderId: '1085913126533',
    projectId: 'music-app-708b7',
    authDomain: 'music-app-708b7.firebaseapp.com',
    storageBucket: 'music-app-708b7.appspot.com',
    measurementId: 'G-CX5MWNGFVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdM9vOjz31dfOb4z64lVqcIUpvJ4zmws',
    appId: '1:1085913126533:android:e09bcd5160b15155763bec',
    messagingSenderId: '1085913126533',
    projectId: 'music-app-708b7',
    storageBucket: 'music-app-708b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdivnXHkI1kG8H2D9YuVvktDNZ5dMW2RQ',
    appId: '1:1085913126533:ios:69bb715de1e4c295763bec',
    messagingSenderId: '1085913126533',
    projectId: 'music-app-708b7',
    storageBucket: 'music-app-708b7.appspot.com',
    iosClientId: '1085913126533-l6m8022nq04snl4l21251sdeovb7fpia.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );
}
